trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  submodules: recursive

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm run build --if-present
  displayName: 'Install and build the project'


